name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start SUT with nohup
        run: |
          nohup java -jar ./artifacts/app-order.jar > app.log 2>&1 &
          echo $! > app.pid
          sleep 15
          cat app.log

      - name: Test with Gradle
        run: |
          ./gradlew test --info
          TEST_EXIT_CODE=$?
          # Останавливаем приложение после тестов
          kill $(cat app.pid) 2>/dev/null || true
          exit $TEST_EXIT_CODE
        env:
          CI: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/test/
            app.log
          retention-days: 30