name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run app
        run: java -jar app-order.jar &
        background: true

      - name: Wait for app to start
        run: |
          timeout 30 bash -c '
          while ! curl -f http://localhost:8080; do
            sleep 1
          done
          '

      - name: Test with Gradle
        run: ./gradlew test --info