name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Start SUT on different port
      run: |
        java -jar ./artifacts/app-order.jar -port=7777 &
        sleep 5
        ps aux | grep java
      
    - name: Test with Gradle
      run: ./gradlew test -Dapp.port=7777
      
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: build/reports/tests/test/
        retention-days: 30
