name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Gradle 7.6
        run: |
          wget -q https://services.gradle.org/distributions/gradle-7.6.4-bin.zip
          unzip -q gradle-7.6.4-bin.zip

      - name: Start SUT with more time
        run: |
          java -jar ./artifacts/app-order.jar &
          echo "Waiting for app to start..."
          sleep 20
          echo "Checking if app is running..."
          netstat -tulpn | grep 9999 || echo "Port 9999 check"
          ps aux | grep java

      - name: Test with Gradle 7.6
        run: |
          ./gradle-7.6.4/bin/gradle test --no-daemon --info

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/test/
            build/test-results/test/
          retention-days: 30